name: Verify

on:
  pull_request:
    branches:
      - master
    paths:
      - 'public/qr/**'
      - 'config.toml'

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v2

      - uses: ./.github/workflows/rust-install

      - name: ⚙ Run verifier
        run: make verifier
